connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password: a

development:
  <<: *connection
  database: workshops_development

test:
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  # password: a
  database: workshops_test

